title: "life in print "
description: Typography Blog
header_text: ""
footer_text: Copyright 2020 Jessica King
header_feature_image: ../uploads/background4.png
bannerheight: 100vh
logo: ../uploads/the-type-logo-4.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - name: profile
    siteurl: /aboutme
    tab: true
